### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by RuthSalvador** [Gabby97/LIM011-data-lovers#15]
Objetivos pendientes:

- Planear y ejecutar tests de usabilidad.
- Manipulación dinámica del DOM.(createElement, appendchild, innerHTML, value)
- Entender la diferencia entre expression y statements. ([LMS](https://lms.laboratoria.la/cohorts/lim-2019-09-bc-core-lim011/courses/javascript/03-functions/01-classic))
- Entender la diferencia entre tipos de datos atómicos y estructurados.
- Organizar y dividir el código en módulos (Modularización).

A partir de estos días quiere enfocarse en estos OA. Se sugiere ver [`fetch`](https://lms.laboratoria.la/cohorts/lim-2019-09-bc-core-lim011/courses/browser/04-xhr/10-fetch) en el caso de tener tiempo adicional.

**Comment by Gabby97** [comment]
Gracias Ruth
